// Asset History/Movement tracking data types and dummy data

export interface AssetHistory {
  id: string;
  serialNumber: number;
  deviceType: string;
  deviceSerialNumber: string;
  userDeployedTo: string;
  locationDeployedTo: string;
  deviceMovement: 0 | 1; // 0 = no movement, 1 = movement
  reasonsForUpdate: string;
  deviceStatusAtStartup: string;
  changedBy: string;
  changeDate: string;
}

// Device types for filtering
export const deviceTypes = [
  "All",
  "Monitor",
  "CPU",
  "POS",
  "Scanner",
  "Tablets",
  "IP Phone",
  "Printer",
  "Laptop",
  "Desktop",
];

// Locations for filtering
export const locations = [
  "All",
  "Head Office",
  "Akute",
  "Surulere",
  "Alaba",
  "Agege",
  "Victoria Island",
  "Ikeja",
  "Lekki",
];

// Device statuses
export const deviceStatuses = [
  "All",
  "Live",
  "Faulty",
  "Unallocated",
  "Under Repair",
  "Disposed",
  "Missing",
];

// Users for filtering
export const users = [
  "All",
  "christian",
  "oamoo",
  "favour",
  "BC",
  "TELLER",
  "HBO",
  "DCO",
  "BM",
  "CS",
  "ACCOUNT OFFICER",
  "CSO",
];

// Generate comprehensive dummy data for asset history
export const assetHistoryData: AssetHistory[] = [
  {
    id: "1",
    serialNumber: 1,
    deviceType: "Monitor",
    deviceSerialNumber: "CN335Q4PN",
    userDeployedTo: "BC",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "2",
    serialNumber: 2,
    deviceType: "CPU",
    deviceSerialNumber: "TRF510HQZ",
    userDeployedTo: "BC",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "3",
    serialNumber: 3,
    deviceType: "POS",
    deviceSerialNumber: "288661060",
    userDeployedTo: "TELLER",
    locationDeployedTo: "Head Office",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "Faulty",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "4",
    serialNumber: 4,
    deviceType: "POS",
    deviceSerialNumber: "012390001357855",
    userDeployedTo: "HBO",
    locationDeployedTo: "Head Office",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "Faulty",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "5",
    serialNumber: 5,
    deviceType: "Scanner",
    deviceSerialNumber: "CN55JD5734",
    userDeployedTo: "DCO",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "6",
    serialNumber: 6,
    deviceType: "CPU",
    deviceSerialNumber: "TRF510HQZ",
    userDeployedTo: "BC",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "7",
    serialNumber: 7,
    deviceType: "CPU",
    deviceSerialNumber: "CNC50932ZVO",
    userDeployedTo: "DCO",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "8",
    serialNumber: 8,
    deviceType: "CPU",
    deviceSerialNumber: "TRF3510T15X",
    userDeployedTo: "HBO",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "9",
    serialNumber: 9,
    deviceType: "CPU",
    deviceSerialNumber: "TRF3510HMI",
    userDeployedTo: "BM",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "10",
    serialNumber: 10,
    deviceType: "CPU",
    deviceSerialNumber: "TRF25107MZ",
    userDeployedTo: "CS",
    locationDeployedTo: "Akute",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "11",
    serialNumber: 11,
    deviceType: "Tablets",
    deviceSerialNumber: "R52H91RKZZT",
    userDeployedTo: "ACCOUNT OFFICER",
    locationDeployedTo: "Head Office",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "Live",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "12",
    serialNumber: 12,
    deviceType: "Tablets",
    deviceSerialNumber: "R52H91RKZZT",
    userDeployedTo: "ACCOUNT OFFICER",
    locationDeployedTo: "Head Office",
    deviceMovement: 0,
    reasonsForUpdate: "ACCOUNT OFFICER(ENIADE JOHNSON) IS LEAVING THE BANK",
    deviceStatusAtStartup: "Live",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "13",
    serialNumber: 13,
    deviceType: "",
    deviceSerialNumber: "",
    userDeployedTo: "",
    locationDeployedTo: "",
    deviceMovement: 0,
    reasonsForUpdate: "",
    deviceStatusAtStartup: "",
    changedBy: "oamoo",
    changeDate: "2018-03-01",
  },
  {
    id: "14",
    serialNumber: 14,
    deviceType: "POS",
    deviceSerialNumber: "012390001357855",
    userDeployedTo: "HBO",
    locationDeployedTo: "Head Office",
    deviceMovement: 0,
    reasonsForUpdate: "ROLLER HAS BEEN DAMAGED AND REMOVED",
    deviceStatusAtStartup: "Faulty",
    changedBy: "christian",
    changeDate: "2018-03-01",
  },
  {
    id: "15",
    serialNumber: 15,
    deviceType: "CPU",
    deviceSerialNumber: "CZC2048H2S",
    userDeployedTo: "BC",
    locationDeployedTo: "Surulere",
    deviceMovement: 1,
    reasonsForUpdate: "Return to surulere after repair of faulty powerpack",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "16",
    serialNumber: 16,
    deviceType: "IP Phone",
    deviceSerialNumber: "687GE765B003042",
    userDeployedTo: "HBO",
    locationDeployedTo: "Alaba",
    deviceMovement: 0,
    reasonsForUpdate: "nothing",
    deviceStatusAtStartup: "Unallocated",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "17",
    serialNumber: 17,
    deviceType: "IP Phone",
    deviceSerialNumber: "687GE765B003029",
    userDeployedTo: "HBO",
    locationDeployedTo: "Agege",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Unallocated",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "18",
    serialNumber: 18,
    deviceType: "Monitor",
    deviceSerialNumber: "CNC209NCMB",
    userDeployedTo: "BC",
    locationDeployedTo: "Alaba",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Unallocated",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "19",
    serialNumber: 19,
    deviceType: "Monitor",
    deviceSerialNumber: "CNC209NSIC",
    userDeployedTo: "Teller",
    locationDeployedTo: "Alaba",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Unallocated",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "20",
    serialNumber: 20,
    deviceType: "Monitor",
    deviceSerialNumber: "CNC209NQZG",
    userDeployedTo: "HBO",
    locationDeployedTo: "Alaba",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "21",
    serialNumber: 21,
    deviceType: "Monitor",
    deviceSerialNumber: "CNC222PWWO",
    userDeployedTo: "BC",
    locationDeployedTo: "Agege",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "22",
    serialNumber: 22,
    deviceType: "Monitor",
    deviceSerialNumber: "6CM31336GK",
    userDeployedTo: "BC",
    locationDeployedTo: "Agege",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "23",
    serialNumber: 23,
    deviceType: "Monitor",
    deviceSerialNumber: "CNC132N2F9",
    userDeployedTo: "CSO",
    locationDeployedTo: "Agege",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "24",
    serialNumber: 24,
    deviceType: "CPU",
    deviceSerialNumber: "CZC2048H2S",
    userDeployedTo: "BC",
    locationDeployedTo: "Surulere",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  {
    id: "25",
    serialNumber: 25,
    deviceType: "CPU",
    deviceSerialNumber: "TRF2490MB2",
    userDeployedTo: "CSO",
    locationDeployedTo: "Alaba",
    deviceMovement: 0,
    reasonsForUpdate: "..",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-02",
  },
  // Additional entries for better pagination testing
  {
    id: "26",
    serialNumber: 26,
    deviceType: "Laptop",
    deviceSerialNumber: "HP789XYZ123",
    userDeployedTo: "Manager",
    locationDeployedTo: "Victoria Island",
    deviceMovement: 1,
    reasonsForUpdate: "Transferred to new branch manager",
    deviceStatusAtStartup: "Live",
    changedBy: "christian",
    changeDate: "2018-03-05",
  },
  {
    id: "27",
    serialNumber: 27,
    deviceType: "Printer",
    deviceSerialNumber: "CANON4562MN",
    userDeployedTo: "ADMIN",
    locationDeployedTo: "Ikeja",
    deviceMovement: 0,
    reasonsForUpdate: "Routine maintenance completed",
    deviceStatusAtStartup: "Under Repair",
    changedBy: "favour",
    changeDate: "2018-03-06",
  },
  {
    id: "28",
    serialNumber: 28,
    deviceType: "Desktop",
    deviceSerialNumber: "DELL892PQR",
    userDeployedTo: "IT Support",
    locationDeployedTo: "Lekki",
    deviceMovement: 1,
    reasonsForUpdate: "Replacement for faulty unit",
    deviceStatusAtStartup: "Live",
    changedBy: "oamoo",
    changeDate: "2018-03-07",
  },
  {
    id: "29",
    serialNumber: 29,
    deviceType: "Monitor",
    deviceSerialNumber: "SAMSUNG445TG",
    userDeployedTo: "Cashier",
    locationDeployedTo: "Head Office",
    deviceMovement: 0,
    reasonsForUpdate: "Screen flickering issue resolved",
    deviceStatusAtStartup: "Under Repair",
    changedBy: "christian",
    changeDate: "2018-03-08",
  },
  {
    id: "30",
    serialNumber: 30,
    deviceType: "Tablets",
    deviceSerialNumber: "IPAD667ABC",
    userDeployedTo: "Field Officer",
    locationDeployedTo: "Victoria Island",
    deviceMovement: 1,
    reasonsForUpdate: "Deployed for customer onboarding",
    deviceStatusAtStartup: "Live",
    changedBy: "favour",
    changeDate: "2018-03-09",
  },
];

// Utility function to format date for history
export const formatHistoryDate = (dateString: string): string => {
  return new Date(dateString).toLocaleDateString("en-NG", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
};
