// Dummy data for Asset List
export interface Asset {
  id: string;
  tagNumber: string;
  assetName: string;
  serialNumber: string;
  category: string;
  department: string;
  branch: string;
  acquisitionDate: string;
  acquisitionCost: number;
  currentBookValue: number;
  status: "Active" | "Disabled" | "Disposed";
  condition: "excellent" | "good" | "fair" | "poor" | "damaged";
  custodian: string;
  location: string;
  supplier: string;
  depreciationStatus: "Current" | "Fully Depreciated" | "Partially Depreciated";
}

// Generate realistic dummy data
export const dummyAssets: Asset[] = [
  {
    id: "1",
    tagNumber: "FA-2024-001",
    assetName: "Dell Latitude 7420 Laptop",
    serialNumber: "DL7420-2024-001",
    category: "Computer Equipment",
    department: "Information Technology",
    branch: "Head Office",
    acquisitionDate: "2024-01-15",
    acquisitionCost: 125000,
    currentBookValue: 118750,
    status: "Active",
    condition: "excellent",
    custodian: "John Smith",
    location: "IT Department - Room 201",
    supplier: "TechCorp Solutions",
    depreciationStatus: "Current",
  },
  {
    id: "2",
    tagNumber: "FA-2024-002",
    assetName: "Executive Office Chair",
    serialNumber: "EOC-2024-002",
    category: "Office Furniture",
    department: "Finance",
    branch: "Head Office",
    acquisitionDate: "2024-02-20",
    acquisitionCost: 45000,
    currentBookValue: 40500,
    status: "Active",
    condition: "good",
    custodian: "Sarah Johnson",
    location: "Finance Department - Office 301",
    supplier: "Office Plus Ltd",
    depreciationStatus: "Current",
  },
  {
    id: "3",
    tagNumber: "FA-2023-045",
    assetName: "Toyota Corolla 2023",
    serialNumber: "TC2023-VIN-12345",
    category: "Vehicles",
    department: "Operations",
    branch: "Branch 1 - Downtown",
    acquisitionDate: "2023-06-10",
    acquisitionCost: 2850000,
    currentBookValue: 2280000,
    status: "Active",
    condition: "good",
    custodian: "Michael Brown",
    location: "Parking Lot A - Slot 15",
    supplier: "Toyota Dealership",
    depreciationStatus: "Current",
  },
  {
    id: "4",
    tagNumber: "FA-2022-089",
    assetName: "Industrial Printer HP LaserJet",
    serialNumber: "HP-LJ-2022-089",
    category: "Office Equipment",
    department: "Human Resources",
    branch: "Head Office",
    acquisitionDate: "2022-03-12",
    acquisitionCost: 85000,
    currentBookValue: 42500,
    status: "Active",
    condition: "fair",
    custodian: "Lisa Anderson",
    location: "HR Department - Print Room",
    supplier: "TechCorp Solutions",
    depreciationStatus: "Partially Depreciated",
  },
  {
    id: "5",
    tagNumber: "FA-2021-156",
    assetName: "Conference Table (12 Seater)",
    serialNumber: "CT12-2021-156",
    category: "Office Furniture",
    department: "Marketing",
    branch: "Branch 2 - Uptown",
    acquisitionDate: "2021-08-25",
    acquisitionCost: 125000,
    currentBookValue: 50000,
    status: "Active",
    condition: "good",
    custodian: "David Wilson",
    location: "Conference Room B - 2nd Floor",
    supplier: "Modern Furniture Inc",
    depreciationStatus: "Partially Depreciated",
  },
  {
    id: "6",
    tagNumber: "FA-2024-012",
    assetName: "iPad Pro 12.9 inch",
    serialNumber: "IPD-PRO-2024-012",
    category: "Computer Equipment",
    department: "Marketing",
    branch: "Head Office",
    acquisitionDate: "2024-03-08",
    acquisitionCost: 95000,
    currentBookValue: 90250,
    status: "Active",
    condition: "excellent",
    custodian: "Emily Davis",
    location: "Marketing Department - Desk 15",
    supplier: "Apple Store",
    depreciationStatus: "Current",
  },
  {
    id: "7",
    tagNumber: "FA-2020-234",
    assetName: "Air Conditioning Unit (5HP)",
    serialNumber: "AC5HP-2020-234",
    category: "Building Equipment",
    department: "Operations",
    branch: "Branch 3 - Westside",
    acquisitionDate: "2020-05-15",
    acquisitionCost: 185000,
    currentBookValue: 0,
    status: "Active",
    condition: "fair",
    custodian: "Robert Garcia",
    location: "Main Hall - Ceiling Mount",
    supplier: "Climate Control Corp",
    depreciationStatus: "Fully Depreciated",
  },
  {
    id: "8",
    tagNumber: "FA-2023-078",
    assetName: "Standing Desk (Electric)",
    serialNumber: "SD-ELEC-2023-078",
    category: "Office Furniture",
    department: "Information Technology",
    branch: "Head Office",
    acquisitionDate: "2023-11-20",
    acquisitionCost: 75000,
    currentBookValue: 67500,
    status: "Active",
    condition: "excellent",
    custodian: "Amanda Chen",
    location: "IT Department - Workstation 8",
    supplier: "Ergonomic Solutions",
    depreciationStatus: "Current",
  },
  {
    id: "9",
    tagNumber: "FA-2019-301",
    assetName: "Security Camera System",
    serialNumber: "SCS-2019-301",
    category: "Security Equipment",
    department: "Operations",
    branch: "Head Office",
    acquisitionDate: "2019-12-10",
    acquisitionCost: 220000,
    currentBookValue: 44000,
    status: "Disabled",
    condition: "poor",
    custodian: "James Rodriguez",
    location: "Security Room - Server Rack",
    supplier: "SecureTech Ltd",
    depreciationStatus: "Partially Depreciated",
  },
  {
    id: "10",
    tagNumber: "FA-2024-025",
    assetName: "Wireless Projector 4K",
    serialNumber: "WP4K-2024-025",
    category: "Presentation Equipment",
    department: "Human Resources",
    branch: "Branch 1 - Downtown",
    acquisitionDate: "2024-01-30",
    acquisitionCost: 65000,
    currentBookValue: 61750,
    status: "Active",
    condition: "excellent",
    custodian: "Maria Lopez",
    location: "Training Room A - Ceiling Mount",
    supplier: "Audio Visual Pro",
    depreciationStatus: "Current",
  },
  {
    id: "11",
    tagNumber: "FA-2023-192",
    assetName: "Multi-Function Copier",
    serialNumber: "MFC-2023-192",
    category: "Office Equipment",
    department: "Finance",
    branch: "Branch 2 - Uptown",
    acquisitionDate: "2023-07-18",
    acquisitionCost: 145000,
    currentBookValue: 116000,
    status: "Active",
    condition: "good",
    custodian: "Kevin Park",
    location: "Copy Center - Ground Floor",
    supplier: "Office Equipment Co",
    depreciationStatus: "Current",
  },
  {
    id: "12",
    tagNumber: "FA-2022-067",
    assetName: "Server Rack Dell PowerEdge",
    serialNumber: "DLPE-2022-067",
    category: "Computer Equipment",
    department: "Information Technology",
    branch: "Head Office",
    acquisitionDate: "2022-09-05",
    acquisitionCost: 385000,
    currentBookValue: 231000,
    status: "Active",
    condition: "good",
    custodian: "Alex Thompson",
    location: "Server Room - Rack C3",
    supplier: "Dell Technologies",
    depreciationStatus: "Current",
  },
  {
    id: "13",
    tagNumber: "FA-2024-003",
    assetName: "Electric Vehicle Charger",
    serialNumber: "EVC-2024-003",
    category: "Building Equipment",
    department: "Operations",
    branch: "Head Office",
    acquisitionDate: "2024-02-14",
    acquisitionCost: 95000,
    currentBookValue: 90250,
    status: "Active",
    condition: "excellent",
    custodian: "Sophie Turner",
    location: "Parking Garage - Station 1",
    supplier: "Green Energy Solutions",
    depreciationStatus: "Current",
  },
  {
    id: "14",
    tagNumber: "FA-2021-445",
    assetName: "Office Desk (L-Shape)",
    serialNumber: "OD-L-2021-445",
    category: "Office Furniture",
    department: "Marketing",
    branch: "Branch 3 - Westside",
    acquisitionDate: "2021-04-22",
    acquisitionCost: 35000,
    currentBookValue: 17500,
    status: "Active",
    condition: "fair",
    custodian: "Ryan Mitchell",
    location: "Marketing Dept - Corner Office",
    supplier: "Workspace Solutions",
    depreciationStatus: "Partially Depreciated",
  },
  {
    id: "15",
    tagNumber: "FA-2018-789",
    assetName: "Backup Generator (25KW)",
    serialNumber: "BG25-2018-789",
    category: "Building Equipment",
    department: "Operations",
    branch: "Head Office",
    acquisitionDate: "2018-11-30",
    acquisitionCost: 450000,
    currentBookValue: 0,
    status: "Disposed",
    condition: "damaged",
    custodian: "Mark Johnson",
    location: "Basement - Generator Room",
    supplier: "Power Systems Inc",
    depreciationStatus: "Fully Depreciated",
  },
];

// Helper functions for filtering and searching
export const assetCategories = [
  "Computer Equipment",
  "Office Furniture",
  "Vehicles",
  "Office Equipment",
  "Building Equipment",
  "Security Equipment",
  "Presentation Equipment",
];

export const assetStatuses = ["All", "Active", "Disabled", "Disposed"];

export const depreciationStatuses = [
  "All",
  "Current",
  "Partially Depreciated",
  "Fully Depreciated",
];

export const departments = [
  "Information Technology",
  "Finance",
  "Human Resources",
  "Marketing",
  "Operations",
];

export const branches = [
  "Head Office",
  "Branch 1 - Downtown",
  "Branch 2 - Uptown",
  "Branch 3 - Westside",
];

// Utility function to format currency
export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

// Utility function to format date
export const formatDate = (dateString: string): string => {
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
};
